name: Public Repo Test
on: [push]

jobs:
  mpmAndMatlabBatch:
    name: MPM + matlab-batch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: davidbuzinski/setup-matlab
          path: .github/actions/setup-matlab
          ref: mpm
      - uses: actions/checkout@v2
        with:
          repository: davidbuzinski/run-command
          path: .github/actions/run-command
          ref: matlab-batch
      - name: Setup Matlab 
        uses: ./.github/actions/setup-matlab
        with:
          release: R2022a
          products: MATLAB Parallel_Computing_Toolbox
      - name: Run Matlab 
        env:
          MATHWORKS_LICENSING_ENDPOINT: dev
        uses: ./.github/actions/run-command
        with:
          command: "disp('yo world');"

  mpmJustMatlab:
    name: MPM test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: davidbuzinski/setup-matlab
          path: .github/actions/setup-matlab
          ref: mpm
      - uses: actions/checkout@v2
        with:
          repository: davidbuzinski/run-command
          path: .github/actions/run-command
          ref: matlab-batch
      - name: Setup Matlab 
        uses: ./.github/actions/setup-matlab
        with:
          release: R2022a
          products: MATLAB
      - name: Run Matlab 
        env:
          MATHWORKS_LICENSING_ENDPOINT: dev
        uses: ./.github/actions/run-command
        with:
          command: "disp('yo world');"

  ematlabAndMatlabBatch:
    name: ematlab + matlab-batch test
    runs-on: windows-latest
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#           os: [ubuntu-latest, windows-latest, macos-latest]
#           release: [R2021a, R2021b, R2022a]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: davidbuzinski/setup-matlab
          path: .github/actions/setup-matlab
          ref: skip-activation
      - uses: actions/checkout@v2
        with:
          repository: davidbuzinski/run-command
          path: .github/actions/run-command
          ref: matlab-batch
      - name: Setup Matlab 
        uses: ./.github/actions/setup-matlab
        with:
          release: R2022a
#             release: ${{ matrix.release }}
      - name: check on stuff
        run: dir "C:\Program Files\MATLAB"
      - name: check on stuff
        run: dir "C:\Program Files\MATLAB\R2022a"
      - name: Run Matlab
        env:
          MATHWORKS_LICENSING_ENDPOINT: dev
        uses: ./.github/actions/run-command
        with:
          command: "disp('yo world');"
                    
#   dockerAndMatlabBatch:
#     name: docker + matlab-batch
#     runs-on: ubuntu-latest
#     container:
#       image: mathworks/matlab:r2021a
#       options: --user 0
#     steps:
#         - uses: actions/checkout@v2
#         - uses: actions/checkout@v2
#           with:
#             repository: davidbuzinski/setup-matlab
#             path: .github/actions/setup-matlab
#             ref: mpm
#         - uses: actions/checkout@v2
#           with:
#             repository: davidbuzinski/run-command
#             path: .github/actions/run-command
#             ref: matlab-batch
#         - name: Missing wget
#           run: |
#             apt-get update && apt-get install -y wget
#         - name: Setup Matlab 
#           uses: ./.github/actions/setup-matlab
#           with:
#             release: R2021a
#             destination: /opt/matlab/
#             products: Parallel_Computing_Toolbox
#         - name: Run Matlab 
#           env:
#             MATHWORKS_LICENSING_ENDPOINT: dev
#           uses: ./.github/actions/run-command
#           with:
#             command: "disp('yo world');"
